### ISSUE TITLE
Icônes des boutons d'actions sur un sujet

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#100]
Je dois m'y reprendre à plusieurs fois pour comprendre le sens des icônes disponibles sous une discussion
![image](https://github.com/lonestone/rolebase.io/assets/32958589/d1b5593b-497e-495c-bee8-6cc9ab187446)

Si les icônes étaient affichées avec leur label ce serait plus simple à comprendre. L'affordance de l'icône pour les décisions est à débattre. J'aime bien le journal des décisions, cela permet d'avoir une vue sur l'actu importante d'un rôle d'un coup d'oeil.

**Comment by Godefroy** [comment]
Oui c'est vrai !
Est-ce qu'un bouton "+" avec un menu avec les options en toutes lettres ne serait pas mieux ?

Concernant les Décisions, je pense qu'il y a un truc à revoir :
- Elles peuvent être utilisées comme un journal de décisions pour suivre l'actu, mais dans ce cas un fil d'actu serait mieux.
- Elles peuvent être utilisées comme politiques de cercles, mais dans ce cas il faudrait peut-être renommer.

**Comment by snipat** [comment]
Tout à fait, ou pourquoi pas un split button avec _Créer une tâche_ par défaut.

Pour le journal des décisions, je rejoins [JohnnyYWD](https://github.com/JohnnyYWD) sur le besoin d'avoir les décisions importantes regroupées en un endroit, avec leur date. Si je veux faire autrement je dois ouvrir chaque réunion passée et consulter toutes les tâches et les sujets. Ce n'est pas prioritaire mais favorise l'onboarding.

Je n'ai pas de besoins particuliers sur un fil d'actu ; sur les politiques de cercles pour l'instant mais si c'était le cas un champ description ou le journal des décisions suffirait.

**Comment by Godefroy** [comment]
C'est fait, j'ai regroupé les boutons dans un menu "Ajouter".

Tu peux consulter les décisions d'un cercle (dernière section du panneau quand on clique sur un cercle).
Tu peux aussi retrouver les derniers ajouts / suppressions / modifications de décisions dans la page "Historique" accessible depuis le menu "Paramètres".

Si tu as d'autres idées pour mieux utiliser et consulter les décisions, je suis à l'écoute 😃 
En attendant, je clôture l'issue.

**Comment by snipat** [comment]
C'est bien, le lien vers le sujet dont découle la décision est d'autant plus utile du coup.
Dans la section Historique du panneau de cercle, la logique de tri des décisions n'est pas apparente, elle est sûrement chronologique, on verra si ça interroge d'autres utilisateurs.
