### ISSUE TITLE
Souci d'overlay sur les icônes de statuts de discussion

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#101]
Lors du scroll sur une réunion qui contient des sujets, les icônes de statuts de discussion s'affichent par-dessus le reste de l'interface en fenêtre modale ou en pleine largeur

![Screen Shot 2023-05-31 at 11 48 55 AM](https://github.com/lonestone/rolebase.io/assets/32958589/2f5d5877-bb26-47d4-80d3-1c44c6aae825)
![image](https://github.com/lonestone/rolebase.io/assets/32958589/0385538e-72e6-46fd-b841-da1270bcdd33)

**Comment by Godefroy** [comment]
Merci !
@Chloengr a corrigé à l'instant avec la PR #92
