### ISSUE TITLE
Bug : impossible de finir le tuto étape 2 (roles)

### ISSUE THREAD

**Issue by RDeluxe** [lonestone/rolebase.io#107]
- si j'ai pas terminé la première, il ne se passe rien en cliquant sur la seconde étape
- elle s'arrête au bout d'un moment (userflow ne trouve pas la target)

```
Userflow.js: Tooltip target not found on page.
 {type: 'AUTO', autoData: {…}, excludeText: true, precision: '1', text: 'Ajouter un membre', …}
```

![CleanShot 2023-06-28 at 14 59 26](https://github.com/lonestone/rolebase.io/assets/2767681/4b5f4d3d-3c1f-4ce2-b8ea-b1743a1acc9f)

**Comment by Godefroy** [comment]
Ca devrait être réglé, mais n'hésite pas à rouvrir le ticket si ça se reproduit.
