### ISSUE TITLE
Bug: encoding texte notifications

### ISSUE THREAD

**Issue by RDeluxe** [lonestone/rolebase.io#108]
Les notifications n'aiment pas les accents apostrophes : 

![CleanShot 2023-07-03 at 15 07 44](https://github.com/lonestone/rolebase.io/assets/2767681/7b32d814-d4ed-47a7-89df-898028582fe4)

**Comment by Godefroy** [comment]
Merci ! Ca devrait être fix avec la PR https://github.com/lonestone/rolebase.io/pull/110
