### ISSUE TITLE
Pouvoir créer des réunions récurrentes

### ISSUE THREAD

**Issue by LudiDrouet** [lonestone/rolebase.io#11]

**Comment by Godefroy** [comment]
On peut maintenant dupliquer une réunion (option dans le menu sur la fiche d'une réunion).
Est-ce que ça conviendrait pour ton besoin ?

La récurrence de réunion implique pas mal de choses, je ne prévois pas de l'implémenter pour le moment.

**Comment by LudiDrouet** [comment]
Pas tout à fait :D 
L'idée est de pouvoir créer des réunions sur une année par exemple, comme on peut faire sur Outlook avec les réu Communication qui ont lieu x1/mois, on peut toutes les planifier à l'avance. 

Sinon, ça ira bien pour le moment :-)

**Comment by Godefroy** [comment]
Il est maintenant possible de créer des réunions récurrentes !

Pour cela, 2 entrées possibles :
- Ouvrir un cercle > Réunions > Réunions récurrentes
- Réunions > Menu "..." > Réunions récurrentes
