### ISSUE TITLE
Bouton "centre de connaissance" qui se superpose au bouton "Envoyer"

### ISSUE THREAD

**Issue by RDeluxe** [lonestone/rolebase.io#114]
![CleanShot 2023-08-07 at 16 39 45](https://github.com/lonestone/rolebase.io/assets/2767681/3ff947cf-a5ca-4ba8-b423-31ddd93f3881)

**Comment by Godefroy** [comment]
J'ai retiré le centre de connaissance (qui n'avait de toute façon aucun contenu).
