### ISSUE TITLE
Pas d'autocompletion avec 1Password

### ISSUE THREAD

**Issue by NoeGrangier** [lonestone/rolebase.io#115]
L'autocomplétion sur le login ne fonctionne pas avec 1Password (Pas essayé avec d'autres gestionnaires de mdp)

Bug sur:
- Macbook Air M1, chrome@latest
- XPS 15, chrome@latest

**Comment by Godefroy** [comment]
Merci pour le bug report, c'est arrangé !

C'était un peu sournois : le formulaire est dans un modale chakra, qui a par défaut trapFocus=true.
Quand on cliquait sur un identifiant proposé par 1Password, le focus était immédiatement repris par la modale sans exécuter le clic.
