### ISSUE TITLE
Où sont les résumés ?

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#120]
Quand on regarde un cercle, on voit la liste des réunions et des décisions. Est-ce qu'il y a un endroit où sont consultables tous les résumés de réunion d'un coup d'oeil ?
Est-ce que l'onglet Notes présent dans chaque déroulé de réunion est utilisé pour le résumé ? Nous remplissons les sujets ou les tâches mais cela n'apparaît pas.

**Comment by Godefroy** [comment]
Hello @snipat 

Les résumés de toutes les réunions terminées s'affiche sur la page Actualités.
Est-ce que ça répond à ton besoin ?

Oui les notes de toutes les parties de la réu (sujets compris) sont utilisées pour générer automatiquement le résumé. Les tâches ne sont en revanche pas utilisées.

**Comment by snipat** [comment]
Merci @Godefroy, en l'occurrence je cherchais à consulter tous les CR d'un coup d'oeil, c'est en effet possible avec le filtrage par rôle sur la home. Je n'ai pas cherché ça dans _Actualités_ car j'ai eu le préjugé que c'était comme un newsfeed et que tout ne serait pas affiché d'un coup. Mon besoin actuel est comblé mais je pense que ça vaut une rubrique au sein de la page cercle.

Pour l'onglet _Notes_, si je comprends bien, il faut utiliser les notes dans chaque pour mettre à jour un sujet… mais est-ce que je retrouverai dans un sujet toutes les notes prises au fil des successions ? Mon besoin est : 

- voir sur un sujet toutes les notes prises dessus
- voir sur un CR toutes les mises à jour des différents sujets

**Comment by Godefroy** [comment]
Bonne idée, je viens d'ajouter un onglet "Actualités" dans le panneau du cercle !

Pour ton autre question, tu parles bien des notes dans un sujet en réunion ?

Tu peux créer un sujet en réunion ou hors réunion, et rattacher des sujets à une réunion dans une section du déroulé de type Sujets.
Lorsque vous parlez d'un sujet pendant une réunion, vous pouvez prendre les notes dans le champ qui s'affiche sous le titre du sujet rattaché.
Ca fait un CR de réunion structuré bien lisible et partageable en interne.
Les notes de toutes la réunion y compris du sujet sont prises en compte par la génération automatique du résumé par IA.
Toutes les notes prises en réunion sur des sujets sont retrouvables dans les sujets concernés. Ainsi on ne perd pas le fil 😃

**Comment by snipat** [comment]
Super, ça répond au besoin.

Si les notes sont ajoutées dans chaque sujet en plus du CR, c’est parfait. J’avais pas compris ça quand j’ai vu le champ de Notes pour la première fois. Ça manquait peut-être d’un tooltip. Merci !

Cordialement,

Patrick
