### ISSUE TITLE
Bug: Synchro Outlook de réunions supprimées

### ISSUE THREAD

**Issue by ClementRivaille** [lonestone/rolebase.io#124]
Suite à la suppression d'un cercle sur Rolebase, ses réunions récurrentes ont bien été retirées du calendrier Rolebase. Mais elles sont encore présentes sur Outlook, d'où il n'est pas possible de les supprimer.
![image](https://github.com/lonestone/rolebase.io/assets/4161503/260bc189-b5e7-4ab1-ba3a-ac5629d176e5)
![image](https://github.com/lonestone/rolebase.io/assets/4161503/7074ffe8-ac6a-4f27-ba5f-2e307225544d)

Le lien inclus dans la description pointe vers une réunion qui n'existe plus.
![image](https://github.com/lonestone/rolebase.io/assets/4161503/ea1cad50-5830-4114-937d-d4b270d086f5)

**Comment by Godefroy** [comment]
Ce bug devrait maintenant être résolu, merci pour le signalement !

Il est toujours possible de supprimer des événements depuis Outlook, ça n'aura pas d'impact sur les réunions dans Rolebase.
