### ISSUE TITLE
Améliorer le système de tâches

### ISSUE THREAD

**Issue by Lythom** [lonestone/rolebase.io#17]
Pour le cercle formation, on a identité qu'on aimerait utiliser le système de tâches de rolabase pour nos indicateurs mais ils manquent des informations nécessaires :
- Pour le statut du ticket, on a besoin d'avoir un statut équivalent à "à faire, non affecté", "en cours, affecté", "terminé". En l'état ça pourrait presque fonctionner avec le modèle de données actuel (en laissant la tâche non faite et en affectant la tâche à quelqu'un dès qu'elle est démarrée) mais ça pourrait difficilement coller avec l'indicateur suivant :    
- nombre de jours dans le statut. (nombre de jours en "à faire", nombre de jour en "affecté"), on a pas besoin du nombre de jours après que la tâche soit terminée. L'objectif ici est d'avoir un indicateur qui nous permette d'identifier les actions qui trainent depuis le plus longtemps pour pouvoir les traiter dans l'ordre et identifier les blocages. A défaut d'un calcul complet, une simple "date de changement de statut" + affichage de la date de création pourrait couvrir le besoin.

**Comment by Godefroy** [comment]
Le système de tâche a été amélioré avec :
- Un statut : À faire / En cours / En revue / Terminée / Bloquée
- L'affichage du membre assigné dans l'aperçu de tâche

Pour le nombre de jours j'ai des doutes sur l'intérêt et la manière de faire.
Il y a déjà un tri des tâches par statut et par date limite. Le nb de jours peut être rajouté dans la description.
Est-ce que ça suffirait pour ton besoin ?

**Comment by Godefroy** [comment]
Il est maintenant possible d'afficher en kanban.
