### ISSUE TITLE
Rendre impossible de cumuler membre + rôle spécifique au sein d'un même cercle.

### ISSUE THREAD

**Issue by soyeloso** [lonestone/rolebase.io#2]
Il y a de l'incertitute niveau usage sur ce point, est-ce que les rôles se cumulent au sein d'un même cercle ou est-ce qu'ils se remplacent ?
Il me semble plus logique de trancher et de rendre impossible le cumule des rôles. Un leader ou facilitateur par exemple est implicitement un membre et n'a pas besoin d'apparaître comme tel dans la représentation.

Est-ce que ça paraît cohérent avec les autres features ?

**Comment by Godefroy** [comment]
En holacratie, par défaut, on ne peut pas avoir de membre direct dans un cercle, chaque membre doit occuper un ou plusieurs rôles.

En sociocratie, il me semble que c'est plus permissif et qu'on peut également avoir des membres directs sans forcément leur assigner un rôle.

Dans l'absolu, il me semble utile de garder cette liberté dans l'outil. Un membre peut être membre direct d'un cercle ou occuper un ou plusieurs rôles dans le cercle.

Pour qu'un membre participe aux discussions et réunions d'un cercle, il n'est donc pas nécessaire de le lister directement dans le cercle s'il occupe un rôle ou s'il est leader d'un sous-cercle dans ce cercle.

Par contre on pourrait expliquer ça et rendre plus lisible la liste des participants dans le panneau d'un cercle pour mieux s'en rendre compte.

Comment ça pourrait être rendu plus clair à ton avis ?

**Comment by soyeloso** [comment]
Oui très bonne idée de rajouter les "participants" à cet endroit ! C'est plus clair effectivement.
