### ISSUE TITLE
Le bold n'est pas assez prononcé dans les éditeurs de texte

### ISSUE THREAD

**Issue by ls-flow** [lonestone/rolebase.io#23]
Lorsque l'on passe un texte en bold, c'est la version medium (je pense) qui apparait. Du coup la différence entre regular/bold n'est pas assez prononcée

**Comment by Godefroy** [comment]
C'est un peu galère avec la police Nunito, je trouve que les différences de weight sont trop subtiles. J'ai déjà tenté de forcer le 700 à plusieurs endroit mais peut-être pas partout.

C'est à quel endroit auquel tu penses ?
