### ISSUE TITLE
Bug visuel lors de la création d'une discussion depuis la note de réunion

### ISSUE THREAD

**Issue by Lythom** [lonestone/rolebase.io#25]
J'ai créée une note de réunion, depuis la note créé une discussion, copié coller le contenu depuis slack. 
Résultat si dessous.
Observé: du texte est rendu sans fond, le background de la modale est tronqué.
Attendu: un arrière plan blanc est présent derrière l'ensemble du texte.
![image](https://user-images.githubusercontent.com/722132/172798170-44e421b6-4fe3-46c4-b2d8-d77c54e15725.png)
![image](https://user-images.githubusercontent.com/722132/172798215-ed062760-b15c-4406-8600-e0b5e07b964c.png)

**Comment by Godefroy** [comment]
Merci ! C'est réglé, peux-tu retester stp ?
