### ISSUE TITLE
Animer le tour d'inclusion avec le toggle de participation

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#30]
Je lance la réunion
Je vois les noms des participants et les switches ci-dessous
Je fais le tour d'inclusion en cochant les switchs au fur et à mesure
![image](https://user-images.githubusercontent.com/32958589/176382042-f5033859-6bf4-41db-bef6-4f50aaff069c.png)

Puis je scolle et j'arrive sur l'inclusion

Demande : inclure les switches dans la section Inclusion (en faire un composant comme Checklist, Discussions, etc)

**Comment by Godefroy** [comment]
C'est fait !

Commit: 17aacf0d5b8dc51ae88c6eafc08697bdc94c9ad6

**Comment by snipat** [comment]
J'ai beau tester et retester, je ne le vois pas. Je note que je ne vois plus l'entrée de menu Modèles de réunion

**Comment by Godefroy** [comment]
Tu as démarré la réunion ?

Les modèles de réunion sont accessible avec l'icône d'édition à droite du champ Modèle quand on crée une réunion. Tu penses qu'il est nécessaire de le garder accessible ailleurs ?

**Comment by snipat** [comment]
Oui ça marche mieux en démarrant la réunion, le déplacement du CTA Démarrer de la modale vers le footer m'a perturbé.
Pour les modèles de réunion, j'avais bien gardé en tête l'accès via le menu et je m'en sers encore beaucoup.
