### ISSUE TITLE
Le texte saisi n'est pas enregistré et perdu en quittant la modale

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#35]

**Comment by snipat** [comment]
Je facilite une réunion
J'ouvre une tâche dans une modale
Je saisis un texte dans le module Description
Je clique à côté de la modale et elle disparaît
Je reviens dans la modale
Le texte saisi a disparu

Contournement : je saisis le texte puis clique à côté du champ ce qui provoque l'apparition du bouton Enregistrement

**Comment by Godefroy** [comment]
Merci pour le feedback !
J'ai retiré le bouton "Enregistrer" et ajouté un auto-save.
