### ISSUE TITLE
Je veux voir le contenu de ma réunion en plus grand

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#36]
Facilitateur, je partage mon écran via visio conférence pour que les utilisateurs aient un seul support de réunion
Je zoome avec le navigatgeur pour que le texte s'affiche en grand
![Capture d'écran 2022-07-12 à 10 01 01 AM](https://user-images.githubusercontent.com/32958589/178448442-9118bc46-4147-472f-a24e-f13f49eab4cc.png)

Le texte s'affiche en grand mais le kanban se décale à cause du zoom
![image](https://user-images.githubusercontent.com/32958589/178448654-e31860e4-f1f6-4956-904b-4658e79c9800.png)

**Comment by Godefroy** [comment]
Oh je vois d'où ça vient ! Ca sera corrigé.
En attendant pour résoudre le problème d'affichage quand tu es dans ce cas de figure, tu peux cliquer sur Liste puis à nouveau sur Kanban.
