### ISSUE TITLE
Je veux créer une checklist à exécuter lors de chaque réunion

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#38]
Facilitateur, je crée un modèle de réunion
J'ajoute une section Checklist
Je crée une réunion et la commence
Je peux ajouter des checkboxes et les cocher ou non lors de la réunion
Je termine la réunion
Je crée une nouvelle réunion et ne retrouve pas ma checklist

Demande : 

**Facilitateur je veux pouvoir éditer une checklist dans un modèle de réunion afin qu'elle soit complétée lors de chaque réunion**. Lorsque je démarre une réunion, la checklist est décochée, lorsque je la ferme les valeurs sont enregistrées. Lorsque je crée une nouvelle réunion, la checklist est à nouveau intégralement décochée.

**Comment by Godefroy** [comment]
J'ai amélioré la découvrabilité en changeant 2 choses :
- La checklist et les indicateurs d'un rôle sont automatiquement utilisés lors de la création d'une réunion. 
- Lorsque le champ est vide et qu'il n'y a pas de valeur configurée dans le rôle, un message informatif apparaît.

Rencontres-tu encore des difficultés avec la checklist ?
