### ISSUE TITLE
Conflit de raccourci entre l'ajout d'URL et la recherche globale

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#41]
J'anime une réunion et saisis du texte
Je souhaite ajouter un hyperlien et saisis CMD+K 
L'éditeur de texte Outline propose l'ajout d'URL mais la recherche globale du site se lance en même temps

Contournement possible en n'utilisant pas le raccourci clavier.
Criticité faible mais c'est déroutant

<img width="912" alt="screenshot_2022-08-23_à_14_21_08" src="https://user-images.githubusercontent.com/32958589/186177570-e2e3c67c-ba2a-4609-afde-cc3f4b6d757d.png">

**Comment by Godefroy** [comment]
Merci pour ce feedback !
J'ai changé le comportement pour que la recherche s'ouvre maintenant avec Ctrl+P (Cmd+P sur Mac) au lieu de Ctrl+K, ce qui ne gène pas l'éditeur. Le comportement par défaut du navigateur (Imprimer) est bloqué, comme sur Notion.
