### ISSUE TITLE
Avoir un statut de discussion

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#43]
Actuellement et en dehors de Rolebase, nous utilisons un kanban pour la gestion des tâches mais aussi celles des tensions.
Cela nous permet de visualiser différents états : brouillon (visible de tous), à l'ordre du jour (du triage ou de la gouvernance) ou règlement asynchrone et terminé.

Sur Rolebase, je peux assigner une tension (discussion) à un cercle mais pas lui donner un état.
De ce fait, toutes les tensions sont mélangées et cela demande un effort pour savoir laquelle ouvrir ou non, notamment en réunion.

Un système de statut comme pour les tâches pourrait résoudre ce problème, pourquoi pas avec un kanban dans une version ultérieure.

NB : nous aurions bien utilisé les tâches pour bénéficier du kanban mais nous l'utilisons déjà pour le suivi des tâches et projets et cela aurait créé de la confusion d'y ajouter les tensions.

**Comment by Godefroy** [comment]
Ça pourrait effectivement être utile.
Aurais-tu une liste exhaustive des statuts dont tu aurais besoin ?

**Comment by snipat** [comment]
En prenant en compte les statuts existants pour les tâches (À faire, en cours, en revue, bloquée, Terminée) mais aussi ceux de Saas similaires : 
- Future, Current, Waiting, Done
- To do, In Progress, Done)
mais aussi nos statuts de tension actuels : 
- Créée, À l'ordre du jour, Règlement asynchrone, Terminé, Rejeté

je suggère : 
1. Ouverte : la discussion est créée et visible de tous mais n'est pas embarquée
2. À l'ordre du jour : pour discussion lors d'une réunion
3. Asynchrone : pour traitement sans réunion physique ou distancielle
4. En attente : la disussion est bloquée (colonne de délestage)
5. Terminée

Concrètement les statuts À l'ordre du jour et Asynchrone seraient une seule et même étape. Cela pour éviter de créer un système d'étiquettes juste pour préciser le mode de discussion.

Un tri de la page des discussions https://rolebase.io/orgs/xxx/threads serait apprécié : 
- lots par cercles (selon leur ordre alphabétique)
- puis lot par statuts (selon l'ordre des étapes)
- puis tri alphabétique
Voici pour mes suggestions 🙌

**Comment by snipat** [comment]
Cette première version des statuts est déjà pas mal !

**Comment by Godefroy** [comment]
On peut maintenant mettre un statut à un sujet, c'est "En préparation" par défaut.
On peut donc aussi trier les sujets par statut.
