### ISSUE TITLE
Voir les tâches même lorsque la réunion n'est pas commencée

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#44]
Facilitateur, je crée une réunion en me basant sur un modèle 
Je ne démarre pas la réunion
Je vois toutes les sections de mon modèle mais la section tâches est vide
Je démarre la réunion
La section tâche se remplit avec le kanban des tâches

**Demande** : afficher le contenu de la section tâches si présente, sinon on peut penser qu'on n'a pas de tâches
Criticité : faible
![Réunions_-_Rolebase](https://user-images.githubusercontent.com/32958589/187885228-086f4e3a-37da-492c-81af-e01766ee1486.png)

**Comment by Godefroy** [comment]
Merci pour le feedback, c'est modifié ;-)
