### ISSUE TITLE
Création de réunion - Pb encodage sur calendar

### ISSUE THREAD

**Issue by Johbrun** [lonestone/rolebase.io#46]
La réunion créée sur Rolebase et importé sur Calendar (Outlook). 
Cependant, la quote est affichée encodée 

![image](https://user-images.githubusercontent.com/31695713/188928915-3fc1cb6d-facd-4c49-8291-2e4006caf535.png)

**Comment by Godefroy** [comment]
Merci pour le feedback, c'est réglé !
