### ISSUE TITLE
License undefined? 

### ISSUE THREAD

**Issue by SamirSaidani** [lonestone/rolebase.io#48]
Hi

I'm very interested in this webapp, I'd be happy to contribute but I can't find any information in the code on the kind of opensource licence you are using. 

Is it possible to clarify the opensource license used on this project?

Thanks!

**Comment by Godefroy** [comment]
Hi Samir,

I just added a [LICENSE](https://github.com/lonestone/rolebase.io/blob/main/LICENSE) file to the repository.
Fell free to ask any question about it.


Au plaisir d'échanger à propos de ton besoin et pourquoi pas prendre un café un jour, je suis pas loin (Nantes) 😄

**Comment by SamirSaidani** [comment]
Hi Godefroy,

Thanks for updating the code with a license.

Unfortunately the license you've chosen - "Fair Source License" - is neither free nor open-source license (see https://fair.io/?a#faq).

This choice does not fit with the core values of the opensource/free community, and as far as I'm concern, I will not contribute to this nice project, and probably nobody in the floss community will. 

This is a shame, because there is currently no open-source alternative for holarchic governance.  

I hope you will reconsider your choice and head towards an opensource license.

Regards,
S.

**Comment by Godefroy** [comment]
Hi Samir,

I think you're right and honestly I'm still exploring possibilities.

Do you have any suggestion about some specific licenses?

**Comment by Thatoo** [comment]
MIT is better than proprietary but I would have expect a copy-left licence such as GPL or [EUPL](https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12) (as it is a european project) for a tool that helps Holacracy, Sociocracy organization...
