### ISSUE TITLE
Un clic sur un lien interne m'oblige à me reconnecter

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#52]
Membre, je clique sur un lien dans Rolebase vers une autre page Rolebase
Je suis redirigé vers la page de [connexion](https://rolebase.io/login) où je reste le temps de la connexion automatique
J'arrive sur le bon contenu

**Comment by Godefroy** [comment]
Est-ce que ça te fait ça avec tous les liens ou certains (lesquels) ?
J'ai remarqué que c'est le cas pour un clic sur une notification, mais le système de notificatoin risque d'évoluer prochainement.

**Comment by snipat** [comment]
Je l'ai constaté pour les liens présents dans une tâche créée depuis une discussion (fonctionnalité ajoutée depuis peu).
Le champ Description de la tâche est pré-peuplé automatiquement avec un lien vers la discussion dont la tâche est issue.

![Tâches_-_Rolebase](https://user-images.githubusercontent.com/32958589/192979450-dadad206-5973-4eb9-8014-3ccecf1459d1.png)

**Comment by Godefroy** [comment]
Ok je vois, ça va être compliqué à arranger pour le moment.
Dans le futur, j'aimerais faire en sorte que les liens internes dans l'éditeur soient détectés et remplacés par des boutons et previews.

**Comment by Godefroy** [comment]
C'est réglé !
