### ISSUE TITLE
Aider à la tenue de réunions de gouvernance 

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#53]
C'est plus une discussion qu'un ticket.

Les rôles élus n'ont pas de dates limite et les secrétaires ne pensent pas toujours à organiser les réunions de gouvernance.
De ce fait, les personnes qui énergisent le rôle le font jusqu'à épuisement et les rôles ne sont pas actualisés ou créés.

**Demande**
Aider à organiser des réunions de gouvernance réccurentes pour une bonne marche holacratique : 
- notifier les secrétaires/rôles sur les dates limites des rôles ?
- voir l'historique d'énergisation des rôles pour éviter que les mêmes personnes soient tout le temps dessus
- créer une section pour faciliter l'élection comme le veut l'holacracy ?

**Comment by Godefroy** [comment]
De bonnes idées !

L'historique des membres occupant un rôle peut tout à fait être implémenté.

Je pourrais aussi ajouter une date limite d'occupation d'un rôle, qui fait apparaître un warning et envoie une notif lorsque la date limite est arrivée.

Pour la facilitation d'élection intégrative / sans candidat, comme pour les décisions intégratives, ça mérite une réflexion.
Idéalement, il faudrait 2 implémentations (ou 2 en 1) : pour les réunions et les discussions, afin de les mener en synchrone ou en asynchrone.

Pour les réunions récurrentes, j'imagine pouvoir ajouter des modèles de réunion dans un cercle/rôle avec une récurrence au format rrule (avec une jolie interface). À chaque fin de réunion, la prochaine sera créée.
Qu'en penses-tu ?

**Comment by snipat** [comment]
La prise de décision intégrative serait très utile et je suppose que des templates Outline peuvent y aider.
L'élection sans candidat, quoique moins prioritaire, me semble plus facilement intégrable.
Le 2 en 1 me semble tentable, quoiqu'il ne faut pas oublier les réunions synchrones avec ou sans membre en distanciel, pour lesquelles le facilitateur saisit parfois des informations à la place des membres connectés.

Ce sont des sujets d'envergure qu'il faudrait fouiller en synchrone.

Pour les réunions récurrentes, cela me semble être un très bon début en attendant une éventuelle sync agenda qui impliquerait à mon sens d'avoir les réunions prévues sur un cycle plus long que n+1 (comme le souhaite [Ludi](https://github.com/lonestone/rolebase.io/issues/11)).

**Comment by Godefroy** [comment]
Il est maintenant possible de créer des réunions récurrentes !

Pour cela, 2 entrées possibles :
- Ouvrir un cercle > Réunions > Réunions récurrentes
- Réunions > Menu "..." > Réunions récurrentes
