### ISSUE TITLE
Changement de mot de passe HS

### ISSUE THREAD

**Issue by picks44** [lonestone/rolebase.io#55]
En voulant changer mon mot de passe, j'ai constaté (j'ai fait 2/3 tests pour être sûr) que la modification ne semblait pas prise en compte en back (côté front tout va bien, on a bien la petite alerte verte).

**Comment by Godefroy** [comment]
Le système d'authentification de Rolebase a complètement changé avec le passage sur Nhost, ça devrait maintenant bien fonctionner.
