### ISSUE TITLE
Enabling browser notifications fails

### ISSUE THREAD

**Issue by RDeluxe** [lonestone/rolebase.io#58]
After clicking on the button, the modal displays "Not found" and my browser does not ask for any permission. So I figure that they are not enabled.

![CleanShot 2022-11-28 at 11 03 05](https://user-images.githubusercontent.com/2767681/204250147-3b3d1543-9fad-4e9e-9777-d13051dd3555.png)

**Comment by unamashana** [comment]
@Godefroy @RDeluxe Hana here from MagicBell. Looks like a misconfiguration from our end - we will push out a fix and write back.

**Comment by unamashana** [comment]
This is now fixed @Godefroy and @RDeluxe. Thanks so much for bringing this to our attention.
