### ISSUE TITLE
Je n'arrive pas à retrouver une discussion que j'ai créé

### ISSUE THREAD

**Issue by RDeluxe** [lonestone/rolebase.io#59]
J'ai crée une discussion dans un cercle.

Elle n'apparait pas dans la liste de "mes discussions"

![CleanShot 2022-11-28 at 11 06 10](https://user-images.githubusercontent.com/2767681/204250694-741e968c-e18b-4b7b-912c-6942c4538ea4.png)

Je la retrouve bien en utilisant le moteur de recherche 

![CleanShot 2022-11-28 at 11 07 59](https://user-images.githubusercontent.com/2767681/204250911-e2e1bdb7-1ebd-493b-bfc5-57cc7d36eb23.png)

**Comment by Godefroy** [comment]
Tu ne fais pas partie des participants à cette discussion, c'est pourquoi elle n'apparaît pas dans ta liste.
Les participants sont modifiables en éditant la discussion.
Tu peux retrouver la discussion cliquant sur "Mes discussions" puis en sélectionnant "Autres discussions".

J'ai conscience que ce n'est pas forcément évident. Pour améliorer l'expérience, est-ce que ça conviendrait d'ajouter un warning quand on crée une discussion dont on ne fait pas partie ?

**Comment by RDeluxe** [comment]
Je pense que par défaut on devrait faire partie d'une discussion que l'on crée. C'est le comportement que j'attendrais, et si j'ai créé une discussion pour d'autres je m'enlève de la liste des participants.

**Comment by RDeluxe** [comment]
Je relance sur ce sujet. J'ai participé dans une discussion, Rolebase devrait alors certainement m'ajouter dans les participants ?

![CleanShot 2023-03-15 at 14 41 01](https://user-images.githubusercontent.com/2767681/225326486-4f53e737-52fb-4580-9ca4-d0d4492d55a1.png)

**Comment by RDeluxe** [comment]
Dans le même genre, il faudrait certainement m'ajouter en tant que participants si c'est moi qui crée la discussion ? Ce n'est pas le cas actuellement

**Comment by Godefroy** [comment]
Il y a maintenant un warning quand on crée un sujet sans faire partie des participants, avec un bouton pour s'ajouter d'un clic.
