### ISSUE TITLE
Overlay on discussions

### ISSUE THREAD

**Issue by snipat** [lonestone/rolebase.io#62]
When clicking on a discussions' members' list, there is an overlay with the edit input field
![Capture d'écran 2022-12-06 à 13 14 50 PM](https://user-images.githubusercontent.com/32958589/205910155-e43e5f4a-575d-45ca-a894-3ac22ae5004c.png)
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/32958589/205910168-aa83b770-3034-4b0e-8a1b-127ed249e071.png">

Blocking only when zooming in with the browser.

**Comment by Godefroy** [comment]
Thanks for the report, I just pushed a fix: d81efbd
