### ISSUE TITLE
Impossible d'envoyer un message sur une discussion sans 1er message

### ISSUE THREAD

**Issue by Johbrun** [lonestone/rolebase.io#68]
Sous firefox : 

- J'ouvre une discussion crée par un tier
- Je tente d'envoyer un message => rien ne se passe
- Affichage d'une erreur en console

![image](https://user-images.githubusercontent.com/31695713/218409437-ad67357d-34b9-482f-83a5-9097e47287f1.png)

**Comment by Godefroy** [comment]
Merci pour le rapport, c'est réglé à l'instant !
