### ISSUE TITLE
Discussions : "field 'lastActivityId' not found in type: 'thread'" 

### ISSUE THREAD

**Issue by picks44** [lonestone/rolebase.io#77]
Je n'arrive plus à afficher les discussions, j'ai cette erreur à l'ouverture de la page https://rolebase.io/lonestone/threads
`field 'lastActivityId' not found in type: 'thread'`

**Comment by Godefroy** [comment]
Merci pour le signalement !
Le bug date de cette nuit, il provient d'une erreur de déploiement Netlify qui fait que le front n'est plus compatible avec le back.
Le déploiement Netlify a planté son build à cause d’un mauvais cache par à jour et donc pas compatible avec un nouveau patch de package. J’ai redeploy en vidant le cache et c’est tout bon.

Problème résolu ✅
