### ISSUE TITLE
Il faudrait pouvoir rapidement visualiser les nouveaux messages dans les discussion où j'ai participé

### ISSUE THREAD

**Issue by RDeluxe** [lonestone/rolebase.io#82]
Comme pour un Notion, je devrais pouvoir en 1 clin d'oeil réaliser que qqun a répondu à une discussion après un de mes messages.

Je ne sais pas si c'est réservé aux participants, cf #59

**Comment by Godefroy** [comment]
C'est déjà le cas mais peut-être pas assez visuel : quand quelqu'un a posté une nouvelle activité dans un sujet où je suis participant, le sujet apparaît en haut de la liste et en gras.
Peut-être qu'un petit point bleu en plus à côté serait plus visuel ?
(et il y a bien sûr les notifications qui sont prévues, ça va venir bientôt)

**Comment by Godefroy** [comment]
Les notifications sont maintenant dispos pour les sujets et ont été passées en haut de la sidebar.
