### ISSUE TITLE
Permettre de créer des taches à la volée dans une note de réunion

### ISSUE THREAD

**Issue by Lythom** [lonestone/rolebase.io#9]
Pendant les réunion on fait souvent émerger des tâches qu'on aimerait créer et lier dans le foulée à la note de réunion. Avoir la possibilité de créer la tâche directement depuis la note serait idéal.

**Comment by Godefroy** [comment]
Yes c'est en cours, j'ai lié la PR 😄

**Comment by Godefroy** [comment]
C'est en prod 🎉
